sudo: true
language: node_js
node_js:
- '8'
cache: yarn
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker-compose build
- docker images
- docker tag camping-guide:latest mckernanin/camping-guide
- docker push mckernanin/camping-guide
env:
  global:
  - secure: itJ1/W8y9ndQA4xPqwCBeRIJZST6OAGttH9sCmmiLcWxyDiNpOOrFsD9IKJGXlO3oBI16JX+xc4M/TwNKljiy2tAwK9josOrT5YeduMOwkQxH1s8ui2euWfjGMZJMzUxLyms2NxuSZllO92HL82eallxT8tJZXeSfdsLcTVkpMcuyJo/C1PYrWV7KoPwZjC39SRjWxu0jXsnYXk6pJOMJoKDFNkicKZTB7rSxATWl53g68beMYiliRtjh4ui3kL0iQEyx+S3+wUp9QynJyUzJvyse31b73fltg7OTafqCgI2d0E3chvu/xnRdxq1O4Xfq+aV9FbhhhUciBwZcEaS9zHmPxow6lrL8SJ5whSB1JQVYCccnzlbFZCsAXW58rcqvqcyeYe38z1FxOcLF1++PDv/F2+7jcQ/oawz5aVGV4kZ3pKMHfAs4hygt99g3A7Uz+mAwobUaMj1lceeRNmBotDwZb+34rLOHT/gnUf7hUCIRwQZalNRRpyiWvPfQcPtljxU393GgOuB7ZgfMt7JrzagS0TOmW9VLEN/E3bAydwoTeTVfbSMdyYYU+NcfF2RO0SoeZPybEgIwYuizWnhlfSXpCyeycudXlHuZt1wzyJYUwZus34IDlrQmtBuMUoKzpnmWspIHYCf4ME2d9zRzkv8BRq3iqjmTKxkR2afiLE=
  - secure: AKhT1WERGCAvkC3o+YPHA/aZRvcbM6rSieesEt9kTPnJTlpRXDQE+c/fx30mEt8s2vv2vLI3xsKt6KyEFlQymOvTUwiEudTnZe2zSh5NaywWFxPNrvt4sPtHEx4yug9DyoIGHDgaxQBoy03cKah+/RZ6cb1szWviFPiW5mV/XOVSJm9VHh4g/c6fcpAAMkOdXdeasgbnbztquam4jXEAdPm2gRwIhfhdgGJtULZqui54RCdk00SwsqneY7sHX1v/qUkd4ACMfYBqrD5fTbEWp+BuwwhDFBO01Hd4+EHDIIFHieyxJazT77LExxiMJzT63oqXgY1CGaF9mwoXvtOYkIL2bnxiiQwtW8VNhkXSBd9MvAGc7nYclhmvlY5nAvUXRv2HpxFHKUHx0hwn+V5LCZ8SUuRNT/ZLR/krdqkr13ZHrFOobf8ROzTtypia5y9Md88vNFdnZ5RT+mmShXNfJkDy0HXiAxnDR5cV7dWE8Tr3FB8d9QVKHKWFYM4JVaFu9WUBnTbbopa03bM/WnSMmStEkDoO1Mo89sPqGr4oYgLTh5vN+gnstBVOmCuo1MrPko2v4+7P3B1GxRPp+tHYRW9acpPP4YrrwzEw0UpboDMFg6oqu7eOuAolD2hSnaDOeFvyyP1wddatte4V8fsaEMqQh9KXjqNbU0zo7S6bpfk=
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key camping-guide@docker.mckernan.in
    ~/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2d08653b77bf_key -iv $encrypted_2d08653b77bf_iv
  -in deploy_key.enc -out ./deploy_key -d
notifications:
  slack:
    secure: UgZzuKE+RqSHjoHPUszTBjb6wgaURhVnuhL8MT8D1KlRPgWV/4qLNwK0Y2IL0lCcT241RC3AbPPQhzWV4rsxiib9YrtqrrkJyu9+99Fj7eI0i3f6DF547SfKLrL+rHYpYFs4qe8G2jhVUTlo2ExetTwwBvZLEAvM4gjSribVW7Pu0JrIKHUJ/6Rp7z8Q/njV1WZ9xc+JTVPk4vb2bVUmMi65eOzWW+cyc220e5bK6j8LtPbEH3kjdoRYXJ2zHylSZ/+ogHvA9KYRnACrQ74m50Pg3R293AgMGoGEaErfxCfsoGAXJ9JF2Cnm7CePR8Belo03mho7/nAXtjEwo8xqqslYJY4Yj+ZMC+OJVU4VowBJJoZC8Skar3zYhsn6mBEip6FliWLi7RkhCJGJj7VmcMk6nSPBwuV8mtCfq8QuXn2irovByLFkOQk7WhmrLsJoMBU2EYpxJzVrAANijMpPwigp9qbx29r6t4uIUmH4P8aNJvyWTvn2opn49AvJoDywtnRup/C+JVcbA2EZWWye+9h/g5zHNj92iXq0uu9avns2zZk0a5679EHK9i23snI+aSoi8fRQDNgF4tSjk5B9G54n+xrSQNDbOlMyd4ynrBLf4gu6sjsSPLQUeMU7dFKVHZfHD5t1fF3nZsEO5pL/LwWi/jLZpzxa5upNIhsEzvI=
