sudo: true
language: node_js
node_js:
- "8"
cache: yarn
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker-compose build
- docker images
- docker tag camping-guide:latest mckernanin/camping-guide
- docker push mckernanin/camping-guide
env:
  global:
  - secure: itJ1/W8y9ndQA4xPqwCBeRIJZST6OAGttH9sCmmiLcWxyDiNpOOrFsD9IKJGXlO3oBI16JX+xc4M/TwNKljiy2tAwK9josOrT5YeduMOwkQxH1s8ui2euWfjGMZJMzUxLyms2NxuSZllO92HL82eallxT8tJZXeSfdsLcTVkpMcuyJo/C1PYrWV7KoPwZjC39SRjWxu0jXsnYXk6pJOMJoKDFNkicKZTB7rSxATWl53g68beMYiliRtjh4ui3kL0iQEyx+S3+wUp9QynJyUzJvyse31b73fltg7OTafqCgI2d0E3chvu/xnRdxq1O4Xfq+aV9FbhhhUciBwZcEaS9zHmPxow6lrL8SJ5whSB1JQVYCccnzlbFZCsAXW58rcqvqcyeYe38z1FxOcLF1++PDv/F2+7jcQ/oawz5aVGV4kZ3pKMHfAs4hygt99g3A7Uz+mAwobUaMj1lceeRNmBotDwZb+34rLOHT/gnUf7hUCIRwQZalNRRpyiWvPfQcPtljxU393GgOuB7ZgfMt7JrzagS0TOmW9VLEN/E3bAydwoTeTVfbSMdyYYU+NcfF2RO0SoeZPybEgIwYuizWnhlfSXpCyeycudXlHuZt1wzyJYUwZus34IDlrQmtBuMUoKzpnmWspIHYCf4ME2d9zRzkv8BRq3iqjmTKxkR2afiLE=
  - secure: AKhT1WERGCAvkC3o+YPHA/aZRvcbM6rSieesEt9kTPnJTlpRXDQE+c/fx30mEt8s2vv2vLI3xsKt6KyEFlQymOvTUwiEudTnZe2zSh5NaywWFxPNrvt4sPtHEx4yug9DyoIGHDgaxQBoy03cKah+/RZ6cb1szWviFPiW5mV/XOVSJm9VHh4g/c6fcpAAMkOdXdeasgbnbztquam4jXEAdPm2gRwIhfhdgGJtULZqui54RCdk00SwsqneY7sHX1v/qUkd4ACMfYBqrD5fTbEWp+BuwwhDFBO01Hd4+EHDIIFHieyxJazT77LExxiMJzT63oqXgY1CGaF9mwoXvtOYkIL2bnxiiQwtW8VNhkXSBd9MvAGc7nYclhmvlY5nAvUXRv2HpxFHKUHx0hwn+V5LCZ8SUuRNT/ZLR/krdqkr13ZHrFOobf8ROzTtypia5y9Md88vNFdnZ5RT+mmShXNfJkDy0HXiAxnDR5cV7dWE8Tr3FB8d9QVKHKWFYM4JVaFu9WUBnTbbopa03bM/WnSMmStEkDoO1Mo89sPqGr4oYgLTh5vN+gnstBVOmCuo1MrPko2v4+7P3B1GxRPp+tHYRW9acpPP4YrrwzEw0UpboDMFg6oqu7eOuAolD2hSnaDOeFvyyP1wddatte4V8fsaEMqQh9KXjqNbU0zo7S6bpfk=
  - secure: RmjMQ0d7qRkSCkCtcENxca0blvXqVl6gBEPPAaGoC93IXu9WG4Eg31BoAhEkwbuNnwJW6xIXIqAGEiyeb19utqMhRZYYTU45JnmxgY/vB+IUYn7wdvH/BOP8ltYws9mHgTHTclxCht12k3YOpbv3BPThlxMOdcnKdcS2f8TrGY7gJNJC5uKf5Q3ty4X3ZzTBAuKA9dre3Wqd9zxXptg6GoisjztuEK01s/HTsBdW9YuSu5h01x96hS7C0AzjOVFwRgCVX/ZrGzbYFsX6NDvzvbRhRjgi3nVZ6DGACopoNW4/QhkUggvmmjytWIlfzy3duU3IMh7qy+RMLXOAAqjA/7fAQfT4WlN8kfuhHVPlSzsfbUbFoBaOn3FYLPsvNqZiiM1uAI3+1lrpR4SWEGcUBva/02izzcpgIMxG1aegYydPo5m/oaZmV+7jegWsA0OOi7NWS0YfIs2hSzySyZ32/CXqEqJc1qhBwCPrbhQMJYMGg8II6jO/CuKfQkiUHAdNroTGeAxTXMFMk3nYFeUM7cwsY/K3muc7YjVEGUOJbs9YKOsgqfcjftzJWSedOE1zaAdrt/RnBMrLxaZREIDqblT2NLSWBmeBqPFUHw8O6sIaCpy+O7I/ci1ppT7KbQ5yWnvRauXtB43h5+KmlbV1H7xvT0EnOCgmBfE0hxuy3Ts=
before_install:
- openssl aes-256-cbc -K $encrypted_2d08653b77bf_key -iv $encrypted_2d08653b77bf_iv
  -in deploy_key.enc -out ./deploy_key -d
deploy:
  provider: script
  skip_cleanup: true
  script: $DEPLOY_COMMAND
  on:
    branch: master
